src/Entity/Partie.php
<?php

namespace App\Entity;

use App\Repository\PartieRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PartieRepository::class)]
class Partie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $Score = null;

    #[ORM\ManyToOne(inversedBy: 'parties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getScore(): ?int
    {
        return $this->Score;
    }

    public function setScore(int $Score): self
    {
        $this->Score = $Score;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
    public function __toString()
    {
        return $this->User;
    }
}

src/Form/PartieType.php
<?php

namespace App\Form;

use App\Entity\Partie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PartieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Score')
            ->add('User')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Partie::class,
        ]);
    }
}

src/Controller/PartieController.php
<?php

namespace App\Controller;

use App\Entity\Partie;
use App\Form\PartieType;
use App\Repository\PartieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/partie')]
class PartieController extends AbstractController
{
    #[Route('/', name: 'app_partie_index', methods: ['GET'])]
    public function index(PartieRepository $partieRepository): Response
    {
        return $this->render('partie/index.html.twig', [
            'parties' => $partieRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_partie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PartieRepository $partieRepository): Response
    {
        $partie = new Partie();
        $form = $this->createForm(PartieType::class, $partie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $partieRepository->save($partie, true);

            return $this->redirectToRoute('app_partie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('partie/new.html.twig', [
            'partie' => $partie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_partie_show', methods: ['GET'])]
    public function show(Partie $partie): Response
    {
        return $this->render('partie/show.html.twig', [
            'partie' => $partie,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_partie_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Partie $partie, PartieRepository $partieRepository): Response
    {
        $form = $this->createForm(PartieType::class, $partie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $partieRepository->save($partie, true);

            return $this->redirectToRoute('app_partie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('partie/edit.html.twig', [
            'partie' => $partie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_partie_delete', methods: ['POST'])]
    public function delete(Request $request, Partie $partie, PartieRepository $partieRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$partie->getId(), $request->request->get('_token'))) {
            $partieRepository->remove($partie, true);
        }

        return $this->redirectToRoute('app_partie_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/partie/_delete_form.html.twig
<form method="post" action="{{ path('app_partie_delete', {'id': partie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ partie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/partie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/partie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Partie{% endblock %}

{% block body %}
    <h1>Edit Partie</h1>

    {{ include('partie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_partie_index') }}">back to list</a>

    {{ include('partie/_delete_form.html.twig') }}
{% endblock %}

templates/partie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Partie index{% endblock %}

{% block body %}
    {#<h1>Partie index</h1> #}

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Score</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for partie in parties %}
            <tr>
                <td>{{ partie.id }}</td>
                <td>{{ partie.score }}</td>
                <td>
                    <a href="{{ path('app_partie_show', {'id': partie.id}) }}">show</a>
                    <a href="{{ path('app_partie_edit', {'id': partie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_partie_new') }}">Create new</a>






    <main>   
  <div class="All"></div>
    <div class="col-size">
           <div class="vert-center" id="carre">
           
                  <div class="container">
                 
                              <button class="btn increase" id="ss">
                                      <p>
To survive, click faster than your shadow!
                                      </p>
<img src={{asset('media/luckycolor.jpg')}} width = 20%>
                                    <div id="timer">
                                    </div>
                                    <span id="counter">0
                                    </span>
                                  </button>
                   
                   </div>
           </div>
      </div>
    </div>

    
</main>

<script>const departMinutes = 1;
let temps = departMinutes * 10;

const timerElement = document.getElementById("timer");

setInterval(() => {
  let minutes = parseInt(temps / 60, 10);
  let secondes = parseInt(temps % 60, 10);

  minutes = minutes < 10 ? "0" + minutes : minutes;
  secondes = secondes < 10 ? "0" + secondes : secondes;

  timerElement.innerText = `${minutes}:${secondes}`;
  temps = temps <= 0 ? 0 : temps - 1;
}, 1000);

const btns = document.querySelectorAll(".btn");
const value = document.querySelector("#counter");

// valeur du compteur initialisée à 0
let count = 0;

btns.forEach((btn) => addListenerForEachButton(btn));

// on ajoute un listener avec le bouton en paramètre
function addListenerForEachButton(btn) {
  console.log("Ajout du listener pour chaque bouton");
  btn.addEventListener("click", () => onButtonClicked(btn));
}

function onButtonClicked(btn) {
  if (btn.classList.contains("increase")) {
    // code à exécuter pour le bouton "increase"
    count++;
    console.log("Click faster than your shadow: " + count);
  }

  // on met à jour l'affichage pour le compteur (value) dans le HTML
  value.textContent = count;
}
</script>



{% endblock %}

templates/partie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Partie{% endblock %}

{% block body %}
    <h1>Create new Partie</h1>

    {{ include('partie/_form.html.twig') }}

    <a href="{{ path('app_partie_index') }}">back to list</a>
{% endblock %}

templates/partie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Partie{% endblock %}

{% block body %}
    <h1>Partie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ partie.id }}</td>
            </tr>
            <tr>
                <th>Score</th>
                <td>{{ partie.score }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_partie_index') }}">back to list</a>

    <a href="{{ path('app_partie_edit', {'id': partie.id}) }}">edit</a>

    {{ include('partie/_delete_form.html.twig') }}
{% endblock %}